export type ActionPromptFamilyReference = {
  key:
    | "split"
    | "opposite"
    | "synonym"
    | "evolve"
    | "pop_culture"
    | "compound"
    | "translate"
    | "abbreviate"
    | "expand"
    | "distill"
    | "simplify"
    | "common";
  title: string;
  description: string;
  triggerWords: string[];
};

export const ACTION_PROMPT_FAMILY_REFERENCES: ActionPromptFamilyReference[] = [
  {
    key: "split",
    title: "Split",
    description: "Split the text itself into the real words it is made from.",
    triggerWords: [
      "split",
      "separate",
      "separation",
      "divide",
      "division",
      "fission",
      "half",
      "halve",
      "break",
      "breakdown",
      "decompose",
      "disassemble",
      "fracture",
      "fragment",
      "fragmentation",
      "subtract",
      "subtraction",
      "remove",
      "removal",
      "difference",
      "extract",
      "peel",
      "carve",
      "detach",
      "dissect",
      "partition",
      "slice",
      "cut",
    ],
  },
  {
    key: "opposite",
    title: "Opposite",
    description: "Return the clearest direct opposite of the dominant idea.",
    triggerWords: [
      "opposite",
      "antonym",
      "inverse",
      "contrary",
      "counter",
      "negate",
      "negation",
      "opposed",
      "negative",
      "contrast",
      "antithesis",
      "reverse",
      "reversed",
      "backward",
      "backwards",
      "undo",
      "invert",
      "inversion",
      "rewind",
      "flip",
    ],
  },
  {
    key: "synonym",
    title: "Synonym",
    description: "Find a synonym, alias, alternate name, or very close word-form variant.",
    triggerWords: [
      "synonym",
      "alias",
      "equivalent",
      "equivalence",
      "term",
      "expression",
      "wording",
      "reword",
      "nickname",
      "moniker",
      "codename",
      "designation",
      "appellation",
      "epithet",
      "thesaurus",
      "paraphrase",
      "rephrase",
      "rename",
    ],
  },
  {
    key: "evolve",
    title: "Evolve",
    description: "Push something toward a stronger, more advanced, or later-stage form.",
    triggerWords: [
      "evolve",
      "evolution",
      "evolutionary",
      "mutate",
      "mutation",
      "adapt",
      "adaptation",
      "develop",
      "development",
      "advance",
      "advancement",
      "growth",
      "improve",
      "improvement",
      "upgrade",
      "progress",
      "progression",
      "transform",
      "transformation",
      "metamorphosis",
      "metamorphose",
      "mature",
      "ascend",
    ],
  },
  {
    key: "pop_culture",
    title: "Pop Culture",
    description: "Turn the clues into one specific recognizable pop culture reference.",
    triggerWords: [
      "pop culture",
      "movie",
      "music",
      "song",
      "album",
      "band",
      "actor",
      "actress",
      "film",
      "tv",
      "television",
      "show",
      "celebrity",
      "fandom",
      "franchise",
      "entertainment",
      "meme",
      "anime",
      "cartoon",
      "hollywood",
    ],
  },
  {
    key: "compound",
    title: "Compound",
    description: "Build a real established compound word or common phrase if one exists.",
    triggerWords: [
      "compound",
      "word",
      "vocabulary",
      "language",
      "dictionary",
      "portmanteau",
      "phrase",
      "spelling",
      "lexicon",
      "linguistics",
      "grammar",
      "name",
      "term",
      "hyphenate",
      "blend",
      "hyphen",
      "fusion",
      "collocation",
    ],
  },
  {
    key: "translate",
    title: "Translate",
    description: "Return a translation or equivalent expression in another familiar form.",
    triggerWords: [
      "translate",
      "translation",
      "interpret",
      "render",
      "gloss",
      "dub",
    ],
  },
  {
    key: "abbreviate",
    title: "Abbreviate",
    description: "Compress something into an acronym, shorthand, or shortened form.",
    triggerWords: [
      "abbreviate",
      "abbreviation",
      "acronym",
      "initialism",
      "initials",
      "shorten",
      "shorthand",
      "contract",
    ],
  },
  {
    key: "expand",
    title: "Expand",
    description: "Spell out a shorthand term into its full recognizable form.",
    triggerWords: [
      "expand",
      "expansion",
      "elaborate",
      "elaboration",
      "unfold",
      "extend",
    ],
  },
  {
    key: "distill",
    title: "Distill",
    description: "Extract the essence, concentrate, or defining core of something.",
    triggerWords: [
      "distill",
      "distilled",
      "distillation",
      "essence",
      "extract",
      "refine",
      "purify",
      "core",
      "gist",
    ],
  },
  {
    key: "simplify",
    title: "Simplify",
    description: "Reduce something to a more basic, direct, or canonical form.",
    triggerWords: [
      "simplify",
      "simple",
      "simplification",
      "basic",
      "reduce",
      "clarify",
      "streamline",
      "plain",
    ],
  },
  {
    key: "common",
    title: "Common",
    description: "Find the most specific thing all inputs truly have in common.",
    triggerWords: [
      "common",
      "commonality",
      "shared",
      "mutual",
      "overlap",
      "intersection",
      "similarity",
      "alike",
    ],
  },
];

export function normalizeActionTrigger(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
