import {
  CATEGORY_MODIFIER_ITEM,
  CATEGORY_MODIFIER_ITEM_ID,
  COMBINE_RESULT_PLACEHOLDER_ITEM,
  CRAFT_ITEM,
  CRAFT_ITEM_ID,
  CREATIVE_ITEM,
  CREATIVE_ITEM_ID,
  EVOLVE_ITEM,
  EVOLVE_ITEM_ID,
  OPPOSITE_ITEM,
  OPPOSITE_ITEM_ID,
  POP_CULTURE_ITEM,
  POP_CULTURE_ITEM_ID,
  SPLIT_ITEM,
  SPLIT_ITEM_ID,
  WORD_COMBINE_ITEM,
  WORD_COMBINE_ITEM_ID,
} from "../types";

export const SPECIAL_ITEMS = [
  CATEGORY_MODIFIER_ITEM,
  CRAFT_ITEM,
  COMBINE_RESULT_PLACEHOLDER_ITEM,
  CREATIVE_ITEM,
  EVOLVE_ITEM,
  POP_CULTURE_ITEM,
  SPLIT_ITEM,
  OPPOSITE_ITEM,
  WORD_COMBINE_ITEM,
] as const;

export const SPECIAL_ITEM_BY_ID = new Map(
  SPECIAL_ITEMS.map((item) => [item.id, item] as const)
);

export const RECIPE_CATALYST_ITEM_IDS = new Set<number>([
  CRAFT_ITEM_ID,
  CREATIVE_ITEM_ID,
  EVOLVE_ITEM_ID,
  POP_CULTURE_ITEM_ID,
  SPLIT_ITEM_ID,
  OPPOSITE_ITEM_ID,
  WORD_COMBINE_ITEM_ID,
]);

export const NON_INGREDIENT_ITEM_IDS = new Set<number>([
  CATEGORY_MODIFIER_ITEM_ID,
  ...RECIPE_CATALYST_ITEM_IDS,
]);
