import {
  ACTION_MODIFIER_ITEM,
  ACTION_MODIFIER_ITEM_ID,
  CATEGORY_MODIFIER_ITEM,
  CATEGORY_MODIFIER_ITEM_ID,
  COMBINE_RESULT_PLACEHOLDER_ITEM,
  CREATIVE_ITEM,
  CREATIVE_ITEM_ID,
} from "../types";

export const SPECIAL_ITEMS = [
  ACTION_MODIFIER_ITEM,
  CATEGORY_MODIFIER_ITEM,
  COMBINE_RESULT_PLACEHOLDER_ITEM,
  CREATIVE_ITEM,
] as const;

export const SPECIAL_ITEM_BY_ID = new Map(
  SPECIAL_ITEMS.map((item) => [item.id, item] as const)
);

export const RECIPE_CATALYST_ITEM_IDS = new Set<number>([CREATIVE_ITEM_ID]);

export const NON_INGREDIENT_ITEM_IDS = new Set<number>([
  ACTION_MODIFIER_ITEM_ID,
  CATEGORY_MODIFIER_ITEM_ID,
  ...RECIPE_CATALYST_ITEM_IDS,
]);
